# Generated by Django 4.2.17 on 2025-01-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='ном')),
                ('harid', models.CharField(max_length=50, verbose_name='ном')),
                ('furush', models.CharField(max_length=50, verbose_name='ном')),
            ],
        ),
    ]
