# Generated by Django 4.2.17 on 2025-01-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='ном')),
                ('harid', models.CharField(max_length=50, verbose_name='харид')),
                ('furush', models.CharField(max_length=50, verbose_name='фуруш')),

            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='furush',
            field=models.CharField(max_length=50, verbose_name='фуруш'),
        ),
        migrations.AlterField(
            model_name='task',
            name='harid',
            field=models.CharField(max_length=50, verbose_name='харид'),
        ),
    ]
